# Site settings
title: Project OpenZaak Samenwerken
description: Een overzicht van het project OpenZaak Samenwerken
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# Kramdown settings
kramdown:
  toc_levels: 2..3

# Plugins
plugins:
  - jekyll-toc
  - jekyll-remote-theme
  
# Table of Contents settings
toc:
  min_level: 2
  max_level: 3
  list_class: "toc-list"
  item_class: "toc-item"
  item_prefix: "toc-"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.0"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
# Supports true (default) or false
heading_anchors: true


# Collections (optional, add if you want to organize content)
# collections:
#    docs:
#      output: true
#      permalink: samenwerken/docs/:path/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "OpenZaak Governance pilot. Distributed by an <a href=\"https://github.com/open-zaak/samenwerken/tree/main/LICENSE.md\">EUPL.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/open-zaak/samenwerken" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from